<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2
name: busbuddy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
<<<<<<< HEAD
<<<<<<< HEAD
name: busbuddy
description: A new Flutter project.

=======
name: bus_buddy
description: "A new Flutter project."
>>>>>>> 91ada8e3ae45d451fda9917c6d014f925e30e54c
=======
name: busbuddy
description: A new Flutter project.

>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
<<<<<<< HEAD
publish_to: "none" # Remove this line if you wish to publish to pub.dev
=======
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
<<<<<<< HEAD
  sdk: ">=3.4.1 <4.0.0"
>>>>>>> 91ada8e3ae45d451fda9917c6d014f925e30e54c
=======
<<<<<<< HEAD
  sdk: ">=2.18.2 <3.0.0"
=======
  sdk: '>=2.18.2 <3.0.0'
>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
>>>>>>> 68562972bec7d14ae995e33f438c8332a2044b6a
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
=======
<<<<<<< HEAD
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
=======
<<<<<<< HEAD
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
=======
<<<<<<< HEAD
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
=======
<<<<<<< HEAD
=======

>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  geolocator: ^11.1.0
  google_maps_flutter: ^2.3.0
  intl: ^0.18.1
  geocoding: ^3.0.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
<<<<<<< HEAD
=======
<<<<<<< HEAD
  flutter_polyline_points: ^1.0.0
>>>>>>> 68562972bec7d14ae995e33f438c8332a2044b6a
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
<<<<<<< HEAD
  http: ^0.13.5
  url_launcher: ^6.1.11
  rxdart: ^0.28.0
  tuple: ^2.0.2
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.4
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dependency_overrides:
  win32: ^5.5.4
=======
<<<<<<< HEAD
  http: ^0.13.5
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.2.18
  rxdart: ^0.28.0
  tuple: ^2.0.2
=======
<<<<<<< HEAD
  http: ^0.13.5
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.2.18
=======
<<<<<<< HEAD
  http: ^0.13.5
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.2.18
=======
<<<<<<< HEAD
=======
  cupertino_icons: ^1.0.6

  intl: ^0.19.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
>>>>>>> 91ada8e3ae45d451fda9917c6d014f925e30e54c
=======
<<<<<<< HEAD
=======
  # image_picker: ^1.0.2
>>>>>>> f14665d864e51132ab3f6380a09b0d255bafd81e
=======
  # image_picker: ^1.0.2
=======
>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
>>>>>>> 68562972bec7d14ae995e33f438c8332a2044b6a
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
<<<<<<< HEAD
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
  flutter_lints: ^3.0.0
>>>>>>> 91ada8e3ae45d451fda9917c6d014f925e30e54c
=======
  flutter_lints: ^2.0.0
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

<<<<<<< HEAD
# The following section is specific to Flutter packages.
flutter:
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD

>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/splash.png
# The following section is specific to Flutter packages.
flutter:
<<<<<<< HEAD
=======
=======
# The following section is specific to Flutter packages.
flutter:
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======

>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
<<<<<<< HEAD
  assets:
    - assets/

flutter_native_splash:
  color: #FFFFFF
  image: assets/splash.png
  background_image: "assets/background.jpg"
  android_12:
    color: #FFFFFF
    image: assets/splash.png
    background_image: "assets/background.jpg"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_icons:
  android: true
  ios: false
  web:
    generate: false

  image_path: "assets/icon/icon.png"

  # To add custom icons to your application, add a custom section, like this:
  # An image asset can refer to one orpl more resolution-specific "variants", see
  # https://flutter.dev/assets-and-imaghes/#resolution-aware
=======
<<<<<<< HEAD
  assets:
    - assets/
=======
<<<<<<< HEAD
  assets:
    - assets/
=======
<<<<<<< HEAD
  assets:
    - assets/
=======
<<<<<<< HEAD
  assets:
    - assets/
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
  assets:
    - assets/
=======
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

<<<<<<< HEAD
>>>>>>> 91ada8e3ae45d451fda9917c6d014f925e30e54c
=======
>>>>>>> 35279862e86385b28ab01148b276f1b391af24d0
>>>>>>> 68562972bec7d14ae995e33f438c8332a2044b6a
>>>>>>> 4d8a1679c8fd3545bb711970263e6223a7d445a4
>>>>>>> 931b82405e7a8edfc4743cbab7ab90b315791c7c
>>>>>>> 7ba61d27233680a6f95338ab6f282461ebdf19c1
>>>>>>> f5b3073b2ee2890b4e12e83149e551d98825494e
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
>>>>>>> cea5cac4621c798d25577eac3c7ecf2e652850e2

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
